App\Entity\Tarea:
  attributes:
    id:
      groups: ['proyecto']
    nombre:
      groups: ['proyecto']
    descripcion:
      groups: ['proyecto']
    dificultad:
      groups: ['proyecto']
    prioridad:
      groups: ['proyecto']
    usuarios: 
      groups: ['proyecto']
    